### ISSUE TITLE
Missing main GAP manuals 

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/gap-docker#11]
I've traced the problem in #5

```
########> Diff in [ "./helpintf.xml", 163, 167 ]
# Input is:
stream := InputTextFile( file );;
# Expected output:
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMeth\
odFound
Error, no 1st choice method found for `InputTextFile' on 1 arguments
########
```

This code

```
dirs := DirectoriesLibrary( "doc/ref" );;
file := Filename( dirs, "manual.six" );;
stream := InputTextFile( file );;  
```

does not work because `file` is fail, and this happens because no documentation is provided. Indeed, GAP container uses gap4r7p9_nopackages.zip archive of the core GAP system without packages, and that archive does not include prebuilt manuals.

What to do? Adding latex packages to gap-docker-base does not look very interesting: you need
- texlive-latex-base
- texlive-latex-recommended
- texlive-latex-extra
- texlive-extra-utils
- texlive-fonts-recommended
- texlive-fonts-extra

and this will increase it further, but we need them only to build manuals. Getting precompiled GAP manuals from elsewhere may be more preferable.

**Comment by sebasguts** [comment]
Adding texlive is not a good idea. Why are those manuals not included in the nopackages tarball?

**Comment by olexandr-konovalov** [comment]
Because that's the nopackages tarball concept :) When you build the main GAP manuals, they may contain references to package manuals, so packages should be around - otherwise references will be unresolved.

Option 1: I provide archive of the `doc` directory somewhere as a drop-in replacement

Option 2: download full GAP source archive and extract `doc` (and packages) from there.

**Comment by olexandr-konovalov** [comment]
I went for option 1 and implemented that in https://github.com/gap-system/gap-container/commit/96c7e4d5da130dfdfcd5760e94afc5a439afd1d3
