### ISSUE TITLE
Why is "sudo" recommended in the README?

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap-docker#2]
I am not using sudo, but rather invoke docker directly, and it works fine. Any particular reasons you reocmmend using it? It feels a bit icky to run something with rights it doesn't seem to need...

**Comment by snim2** [comment]
If you are on Ubuntu and have installed the `docker.io` package then you may have to always run `docker` with `sudo`. Otherwise, it is preferable to avoid `sudo`, as you say.

Hopefully the PR I just pushed clarifies this.

**Comment by olexandr-konovalov** [comment]
Thanks - I've merged PR #3
