### ISSUE TITLE
UnitLib is unable to save files

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/gap-docker#8]
My UnitLib package uses `SingleHTTPRequest` from IO to save data for groups of order 243 from the server into `unitlib/data`. It also has functionality for saving computed groups into `unitlib/userdata`. This assumes that the user has write access to those directories. 

```
gap> PcNormalizedUnitGroupSmallGroup(243,1);
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `Length' on 1 arguments called from
Length( code[1] ) called from
<function "PcNormalizedUnitGroupSmallGroup">( <arguments> )
 called from read-eval loop at line 2 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> code;
[ fail, [ [ [ 1, 1 ], [ 2, 1 ], [ 3, 1 ], [ 4, 1 ], [ 5, 1 ] ], [ 1, 3, 9, 27, 81 ] ] ]
brk> 
```

**Comment by olexandr-konovalov** [comment]
Wait, this error message seems to be a network problem. But now is an example showing that the problem with not having write access is genuine: 

```
gap> SavePcNormalizedUnitGroup( SmallGroup( 128, 1 ) );
WARNING : the normalized unit group V(KG) of the modular group algebra 
 of the given group <G> is already included in the library and 
You can access it using the function PcNormalizedUnitGroupSmallGroup.
The description you are going to generate will be stored in the directory 
unitlib/userdata, but will be not used by PcNormalizedUnitGroupSmallGroup. 
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `SetPrintFormattingStatus' on 2 arguments called from
SetPrintFormattingStatus( output, false ); called from
<function "SavePcNormalizedUnitGroup">( <arguments> )
 called from read-eval loop at line 3 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue
brk> 
```

**Comment by olexandr-konovalov** [comment]
I think this requires the same approach as #9: get network and document how to use it in README.md, and set appropriate permissions for the two subdirectories with data files.

**Comment by sebasguts** [comment]
This will soon be closed by https://github.com/gap-system/gap-container/commit/77fee064323ea3c882656f0e4d03e2fc6912111e and some commit I am holding back until gap-docker-base was rebuild using the new container.

**Comment by olexandr-konovalov** [comment]
The problem with saving files resolved here: https://github.com/gap-system/gap-container/issues/5

The other problem is that one should set up network access from the container - it should be documented how to do this and there is a TODO item for this in issue #7.
