### ISSUE TITLE
Getting AtlasRep to work

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-system/gap-docker#9]
AtlasRep package provides a link between GAP and the "ATLAS of Group Representations", a database that comprises generating permutations and matrices for many almost simple groups, and information about their maximal subgroups. This database is available independently of GAP athttp://brauer.maths.qmul.ac.uk/Atlas

To work, first of all this package need network access. Then installation instructions at http://www.math.rwth-aachen.de/~Thomas.Breuer/atlasrep/doc/chap4.html tells:

After unpacking the package archive, it should be checked whether the subdirectories `datagens` and `dataword` of the package directory have write permissions for those users who will download files from the servers. The recommended permissions under UNIX are set as follows.

```
you@unix> chmod 1777 atlasrep/data*
you@unix> ls -ld atlasrep/data*
drwxrwxrwt   3 you      you          1024 Oct 31 12:34 datagens
drwxrwxrwt   3 you      you          1024 Oct 31 12:34 dataword
```

We should follow instructions and run `chmod` in `InstPackages.sh` script.

**Comment by olexandr-konovalov** [comment]
This should be fixed in https://github.com/gap-system/gap-container/issues/5. The other problem is that one should set up network access from the container - it should be documented how to do this and there is a TODO item for this in issue #7.

**Comment by sebasguts** [comment]
Is network access really a problem? I think on Linux systems it works out-of-the-box. Maybe the problem is OS X here?

**Comment by olexandr-konovalov** [comment]
This is Ubuntu. I think I need to use some option to start the container, but I don't know which. @snim2 do you have a pointer, please?

**Comment by sebasguts** [comment]
Try --net="host"
